name: Checkout
on:
  workflow_call:
    inputs:
      stage:
        description: Stage
        type: string
        required: true
      reference:
        description: Reference
        type: string
        default: ''
      hotfix:
        description: Is hotfix
        type: boolean
        default: false
jobs:
  checkout:
    runs-on: ubuntu-20.04
    name: Checkout
    steps:
      - uses: actions/checkout@v2
        name: Branch Checkout
        with:
          submodules: 'recursive'
      - uses: NoorDigitalAgency/release-startup@main
        id: startup
        name: Startup
        with:
          stage: ${{ inputs.stage }}
          reference: ${{ inputs.reference }}
          hotfix: ${{ inputs.hotfix }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo '${{ steps.startup.outputs.version }}'
          echo '${{ steps.startup.outputs.previousVersion }}'
      - uses: actions/checkout@v2
        name: Commit Checkout
        with:
          ref: ${{ steps.startup.outputs.previousVersion }}
          submodules: 'recursive'
