name: Check and Checkout
on:
  workflow_call:
    inputs:
      stage:
        description: Targeted Stage
        type: string
        required: true
      commit:
        description: Commit ID to check out
        type: string
        required: false
        default: ''
    outputs:
      succeeded:
        description: '"true" if succeeded, "false" if failed'
        value: ${{ jobs.check.outputs.result }}
jobs:
  check:
    runs-on: ubuntu-20.04
    name: Check and Checkout
    outputs:
      succeeded: ${{ steps.result.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        name: Analyzing
        with:
          script: |
              const stage = '${{ inputs.stage }}'.toLowerCase().trim();
              const branch = stage === 'alpha' ? 'develop' : stage === 'beta' ? 'release' : 'main';
              const attached = inputs.commit.trim() !== '' && inputs.commit.trim() !== branch;
              await exec.exec('git', ['fetch', '--all']);
              const correctBranch = !detached || (await exec.getExecOutput('git', ['branch', '-r', '--contains', '${{ github.event.inputs.commit }}']))
                        .stdout.split('\n').filter(line => line.trim() !== '').map(line => line.trim().split('/').pop()).includes(branch);
