name: Check and Checkout
on:
  workflow_call:
    inputs:
      stage:
        description: Targeted Stage
        type: string
        required: true
      commit:
        description: Commit ID to check out
        type: string
        required: false
        default: ''
    outputs:
      succeeded:
        description: '"true" if succeeded, "false" if failed'
        value: ${{ jobs.check.outputs.result }}
jobs:
  check:
    runs-on: ubuntu-20.04
    name: Check and Checkout
    outputs:
      succeeded: ${{ steps.result.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        id: analyzing
        name: Analyzing
        with:
          script: |
              const stage = context.payload.inputs.stage.toLowerCase().trim();
              const commit = context.payload.inputs.commit.trim();
              const branch = stage === 'alpha' ? 'develop' : stage === 'beta' ? 'release' : 'main';
              const detached = commit !== '' && commit !== branch;
              await exec.exec('git', ['fetch', '--all']);
              const correctBranch = !detached || (await exec.getExecOutput('git', ['branch', '-r', '--contains', commit]))
                                                 .stdout.split('\n').filter(line => line.trim() !== '').map(line => line.trim().split('/').pop())
                                                 .includes(branch);
              return { stage, branch, detached, correctBranch, commit };
      - if: (fromJSON(steps.analyzing.outputs).detached && fromJSON(steps.analyzing.outputs).correctBranch)
        uses: actions/checkout@v2
        with:
          ref: ${{ fromJSON(steps.analyzing.outputs).commit }}
