name: Deploy
on:
  workflow_call:
    inputs:
      stage:
        description: Stage
        type: string
        required: true
      version:
        description: Deployment Version
        type: string
        required: true
      resourceType:
        description: Kubernetes Resource Type
        type: string
        required: true
      kubectlVersion:
        description: Kubectl Version
        type: string
        required: true
    secrets:
      dockerHubUsername:
        description: Docker Hub Username
        required: true
      dockerHubPassword:
        description: Docker Hub Password
        required: true
      kubeConfig:
        description: Base64 Encoded Kube Config File
        required: true
jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy
    steps:
      - id: analyzing
        name: Analyzing
        uses: actions/github-script@v6
        with:
          script: |
            const name = context.payload.repository.name;
            const label = context.payload.inputs.stage !== 'production' ? `-${ context.payload.inputs.stage }` : '';
            return {
              tags: `noorteam/${ name }:v${ context.payload.inputs.version },noorteam/${ name }:latest${ label }`,
              resource: `${ context.payload.inputs.resourceType }/${ name }${ label }`
            };
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.dockerHubUsername }}
          password: ${{ secrets.dockerHubPassword }}
      - name: Docker Hub Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ fromJson(steps.analyzing.outputs.result).tags }}
          build-args: E20R_ENV=${{ inputs.stage }}
      - name: Kubernetes Resource Update
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.kubeConfig }} | base64 --decode > ~/.kube/config
          curl -LO https://dl.k8s.io/release/${{ inputs.kubectlVersion }}/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          ./kubectl rollout restart ${{ fromJson(steps.analyzing.outputs.result).resource }} --namespace=noor
