name: Parent Workflow
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
    secrets:
      token:
        required: true
jobs:
  job:
    runs-on: ubuntu-20.04
    #if: github.event.release.target_commitish != 'tomato' && github.event.release.target_commitish != 'carrot'
    steps:
      - name: Fail
        run: |
          echo "Wrong branch ${{github.event}}"
          # exit 1
