name: Parent Workflow
on:
  workflow_call:
jobs:
  check:
    runs-on: ubuntu-20.04
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - uses: actions/github-script@master
        with:
          script: console.log(context)
      - id: check
        uses: actions/github-script@master
        with:
          script: return (context.eventName === 'release' && (context.payload.action !== 'published' || (context.payload.release.target_commitish !== 'main' && context.payload.release.target_commitish !== 'develop'))) || (context.eventName === 'workflow_dispatch' && (context.ref !== 'refs/heads/main' && context.ref !== 'refs/heads/develop'))
