name: Publish
on:
  workflow_call:
    inputs:
      stage:
        description: Stage
        type: string
        required: true
      commit:
        description: Commit Id
        type: string
        default: ''
      resourceType:
        description: Kubernetes Resource Type
        type: string
        required: true
      kubectlVersion:
        description: Kubectl Version
        type: string
        default: v1.21.11
    secrets:
      dockerHubUsername:
        description: Docker Hub Username
        required: true
      dockerHubPassword:
        description: Docker Hub Password
        required: true
      kubeConfig:
        description: Base64 Encoded Kube Config File
        required: true
jobs:
  startup:
    runs-on: ubuntu-20.04
    name: Startup
    outputs:
      arguments: ${{ steps.startup.outputs.result }}
    steps:
      - id: startup
        uses: actions/github-script@v6
        name: Startup
        with:
          script: |
              const stage = context.payload.inputs.stage.toLowerCase().trim();
              if (!['production', 'beta', 'alpha'].includes(stage))
              {
                core.setFailed(`Invalid stage name '${stage}'.`);
                return;
              }
              const resource = context.payload.inputs.resourceType.toLowerCase().trim();
              if (!['deployments', 'deployment', 'deploy', 'daemonsets', 'daemonset', 'ds'].includes(resource))
              {
                core.setFailed(`Invalid resource type '${resource}'.`);
                return;
              }
              const commit = context.payload.inputs.commit.toLowerCase().trim();
              const kubectl = context.payload.inputs.kubectlVersion.toLowerCase().trim();
              return { stage, resource, commit, kubectl };
  version:
    needs: [startup]
    uses: NoorDigitalAgency/workflowpedia/.github/workflows/version.yaml@main
    with:
      stage: ${{ fromJSON(needs.startup.outputs.arguments).stage }}
