name: Publish
on:
  workflow_call:
    inputs:
      stage:
        description: Stage
        type: string
        required: true
      commit:
        description: Commit Id
        type: string
        default: ''
      resourceType:
        description: Kubernetes Resource Type
        type: string
        required: true
      kubectlVersion:
        description: Kubectl Version
        type: string
        default: v1.21.11
    secrets:
      dockerHubUsername:
        description: Docker Hub Username
        required: true
      dockerHubPassword:
        description: Docker Hub Password
        required: true
      kubeConfig:
        description: Base64 Encoded Kube Config File
        required: true
jobs:
  versioning:
    runs-on: ubuntu-20.04
    name: Versioning
    outputs:
      version: ${{ steps.generating.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: generating
        name: Generating
        with:
          script: |
              const stage = context.payload.inputs.stage;
              if (stage !== 'production' && stage !== 'beta' && stage !== 'alpha')
              {
                core.setFailed(`Invalid stage name '${stage}'.`);
                return;
              }
