name: Release
on:
  workflow_call:
    inputs:
      stage:
        description: Stage
        type: string
        required: true
      commit:
        description: Commit Id
        type: string
        default: ''
      version:
        description: Release Version
        type: string
        required: true
jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
      - id: analyzing
        name: Analyzing
        uses: actions/github-script@v6
        with:
          script: |
            const releases = [];
            let page = 1;
            let count;
            do
            {
              const data = (await github.rest.repos.listReleases({ owner: context.repo.owner, repo: context.repo.repo, page, per_page: 100 })).data;
              count = data.length;
              releases = releases.concat(data.map(release => ({tag: release.tag_name, branch: release.target_commitish, creation: new Date(Date.parse(release.created_at))})));
              page++;
            } while (count > 0);
            console.log(JSON.stringify(releases));
            // [{"name":"v0.1"}]
            console.log(JSON.stringify((await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            })).data))
            // {"name":"v0.9.4","body":"**Full Changelog**: https://github.com/NoorDigitalAgency/lightning-test/compare/v0.9.2...v0.9.4"}
            console.log(JSON.stringify((await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v0.9.4',
              target_commitish: '${{ github.event.inputs.commit }}',
              previous_tag_name: 'v0.9.2'
            })).data))
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v0.9.2',
              target_commitish: '${{ github.event.inputs.commit }}',
              prerelease: false,
              generate_release_notes: true
            })
            
