name: Release
on:
  workflow_call:
    inputs:
      stage:
        description: Stage
        type: string
        required: true
      commit:
        description: Commit Id
        type: string
        default: ''
      version:
        description: Release Version
        type: string
        required: true
      previousVersion:
        description: Previous Release Version
        type: string
        required: true
jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
      - id: analyzing
        name: Analyzing
        uses: actions/github-script@v6
        with:
          script: |
            const version = context.payload.inputs.version;
            const previousVersion = context.payload.inputs.previousVersion;
            const branch = context.payload.inputs.stage === 'alpha' ? 'develop' : context.payload.inputs.stage === 'beta' ? 'release' : 'main';
            const prerelease = branch !== 'main';
            const releaseNotes = (await github.rest.repos.generateReleaseNotes({ owner: context.repo.owner, repo: context.repo.repo, tag_name: version, target_commitish: branch, previous_tag_name: previousTag })).data;
            await github.rest.repos.createRelease({ owner: context.repo.owner, repo: context.repo.repo, tag_name: version, target_commitish: branch, prerelease, generate_release_notes: false, ...releaseNotes });
            
