name: Release
on:
  workflow_call:
    inputs:
      stage:
        description: Stage
        type: string
        required: true
      commit:
        description: Commit Id
        type: string
        default: ''
jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
      - id: analyzing
        name: Analyzing
        uses: actions/github-script@v6
        with:
          script: |
              // [{"tag_name": "v0.99.0", "target_commitish": "main"}]
              console.log(JSON.stringify((await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
              })).data))
