name: Version
on:
  workflow_call:
    inputs:
      stage:
        description: Stage
        type: string
        required: true
    outputs:
      version:
        description: Generated Version
        value: ${{ jobs.versioning.outputs.version }}
jobs:
  versioning:
    runs-on: ubuntu-20.04
    name: Versioning
    outputs:
      version: ${{ steps.generating.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: generating
        name: Generating
        with:
          script: |
              return `v2030.1-${context.payload.inputs.stage}`;
