name: Version
on:
  workflow_call:
    inputs:
      stage:
        description: Stage
        type: string
        required: true
jobs:
  checkout:
    runs-on: ubuntu-20.04
    name: Checkout
    steps:
      - uses: actions/github-script@v6
        id: analyzing
        name: Analyzing
        with:
          script: |
              const stage = context.payload.inputs.stage.toLowerCase().trim();
              const commit = context.payload.inputs.commit.trim();
              const branch = stage === 'alpha' ? 'develop' : stage === 'beta' ? 'release' : 'main';
              const detached = commit !== '' && commit !== branch;
              await exec.exec('git', ['fetch', '--all']);
              const correctBranch = !detached || (await exec.getExecOutput('git', ['branch', '-r', '--contains', commit]))
                                                 .stdout.split('\n').filter(line => line.trim() !== '').map(line => line.trim().split('/').pop())
                                                 .includes(branch);
              return { stage, branch, detached, correctBranch, commit };
